# Generated by Django 5.2 on 2025-04-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='paintings/')),
                ('year', models.CharField(max_length=10)),
                ('medium', models.CharField(max_length=100)),
                ('dimensions', models.CharField(max_length=100)),
            ],
        ),
    ]
