# Generated by Django 5.2 on 2025-04-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinesePainting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='chinesepaintings/')),
                ('year', models.CharField(max_length=10)),
                ('medium', models.CharField(max_length=100)),
                ('dimensions', models.CharField(max_length=100)),
            ],
        ),
    ]
